color: null
description: null
fieldLayouts:
  173af91e-9110-4244-a0e6-5c024f473dd1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 70395f0a-cf4d-437f-91a5-3d65d785bbe2 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d2bb7ff-afee-4d5f-9e26-94911e738033
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 8438e27f-4863-4220-a584-8d088ce182ab # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff10416f-71f5-4ed3-a46b-fd3aa02c45fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: d105b363-6108-4e77-b353-9b3752ebab2d # Location
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e39a4fa9-790e-4c98-92ac-f674f96b72a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: d0819daa-6a14-48c3-9919-4bb45271707a # Date Taken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a094c55-0b10-485c-9775-43bec6a92e2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 3f1e7923-cbe6-48b6-b426-d0f7df1e7a0b # Locations
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 520c58bb-c639-4b91-83b3-2071e7b017da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f8301bb1-1d58-4742-8341-1bf9a652c516
        userCondition: null
handle: album
hasTitleField: false
icon: null
name: Album
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
