color: null
description: null
fieldLayouts:
  97111621-f62a-439d-9777-a5900718a0e2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-19T01:24:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 51ef19ba-275c-4ce1-b7a3-0013479d2867
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-19T01:18:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 70395f0a-cf4d-437f-91a5-3d65d785bbe2 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19fb8caa-0db2-440f-952c-ae967fb295cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-19T01:19:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e9239899-3d1b-43b5-9e01-b3e860ef5cde # Post Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 162716c1-f41e-4aed-9ff8-1c703f3b9200
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-19T01:18:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8438e27f-4863-4220-a584-8d088ce182ab # Post Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d04badc-a7e5-4a24-ba1e-6fdcb3e770d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-19T01:18:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8369934-e74d-4827-87e1-6610147ec228 # Blog Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72afc436-4b3c-4e74-ba76-7cbab3c1e80e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-19T01:18:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f1e7923-cbe6-48b6-b426-d0f7df1e7a0b # Locations
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a22ad132-6da9-4ea4-b53d-1b3ec3c62eb0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93aa253c-d79c-4fc0-a8d2-dc4f30209ac7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-19T01:18:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3166e34f-44f7-4855-bf97-2c056d085f88
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94a52e18-4541-4fd5-87d4-6529bf91657e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-19T01:18:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e8cd156-1f43-4e98-9720-0906a7ce215d # Related Travels
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebd4e741-29b0-4800-a108-7b2edd76606a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-19T01:18:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: acb6679d-257d-41b7-acd1-d344aab953aa # Related Photography Albums
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e349727d-b50c-449b-8320-f1a511564336
            userCondition: null
            warning: null
            width: 100
        name: 'Related Content'
        uid: e5d877a3-7919-4cb4-927e-e84152eb563e
        userCondition: null
handle: blogPost
hasTitleField: true
icon: null
name: 'Blog Post'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
