color: null
description: null
fieldLayouts:
  3127d006-402c-4991-bd57-5a71a20c721a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 70395f0a-cf4d-437f-91a5-3d65d785bbe2 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65344ec5-4f68-4eeb-b3a5-375c336cba37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 85343b01-dd3a-4e2e-a63c-1fc064dce929 # Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d373c80-ca05-4469-a0f8-6a3b6abe7bbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 8438e27f-4863-4220-a584-8d088ce182ab # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 520cea3c-0777-4b0c-9f61-c8532935b997
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: b31a2d54-562f-4a51-9766-5102a14ea842 # Client
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6519ce9c-8b8b-4b6b-8841-6e9236abe45a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: f847a4de-d05c-499a-aaa4-27a2f47d6091 # Project Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d63ab1d-defe-49a4-9ff4-dd2b337f6191
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 76358275-968c-4a0c-a3ec-6368095a2670 # Creative Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf793c6a-55fc-4967-952b-58aa09a1e39a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3825e51d-f84e-4b0b-b8c3-179e2aa79d15
        userCondition: null
handle: other
hasTitleField: false
icon: null
name: Other
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
