defaultPlacement: end
fieldLayouts:
  3684ad0d-d4c4-4091-96cf-c0088bde69d4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 18710c70-00a4-496c-adc3-4103e8860f7d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4dca20c2-a09e-421c-b079-e2a98eaf5d39
        userCondition: null
handle: locations
name: Locations
siteSettings:
  6e605420-9aed-4e3a-92c7-085d0befa62c: # Personal Website
    hasUrls: true
    template: locations/_category
    uriFormat: 'locations/{slug}'
structure:
  maxLevels: 3
  uid: e80da32d-c54c-4ed1-9f5b-a8b109017a4b
