altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4f2a5da2-a08a-4302-92e3-e5b5a04c3b1a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-18T22:32:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 65a5b70e-723f-45f7-ac03-fc8edf8e81e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50972c0b-3c52-4a96-83d1-cd103e496338
        userCondition: null
fs: uploads
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: ''
