columnSuffix: null
handle: postSummary
instructions: 'A brief summary or excerpt (1-2 sentences)'
name: 'Post Summary'
searchable: false
settings:
  byteLimit: null
  charLimit: 300
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Enter a brief summary...'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
