defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 274ddf00-152f-4298-b17d-8702d2121230 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6e605420-9aed-4e3a-92c7-085d0befa62c: # Personal Website
    enabledByDefault: true
    hasUrls: true
    template: about/index
    uriFormat: about
type: single
