defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 48906ee2-8bd3-4c60-b829-3ce41725cfae # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6e605420-9aed-4e3a-92c7-085d0befa62c: # Personal Website
    enabledByDefault: true
    hasUrls: true
    template: contact/index
    uriFormat: contact
type: single
