defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6ea259f9-7fbf-4638-88b4-5029893c504e # Freelance Project
handle: freelanceWork
maxAuthors: 1
name: 'Freelance Work'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6e605420-9aed-4e3a-92c7-085d0befa62c: # Personal Website
    enabledByDefault: true
    hasUrls: true
    template: freelance/_entry
    uriFormat: 'freelance/{slug}'
type: channel
