defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8856cbd1-2d70-4498-8c89-0deee5fb2335 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6e605420-9aed-4e3a-92c7-085d0befa62c: # Personal Website
    enabledByDefault: true
    hasUrls: true
    template: home/index
    uriFormat: __home__
type: single
