defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6168c004-6475-43f6-846f-2110cf4902e9 # Album
  -
    uid: a7c2870d-87a1-4e8f-a876-8444944dfd66 # Photo
handle: photography
maxAuthors: 1
name: Photography
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6e605420-9aed-4e3a-92c7-085d0befa62c: # Personal Website
    enabledByDefault: true
    hasUrls: true
    template: photography/_entry
    uriFormat: 'photography/{slug}'
structure:
  maxLevels: 2
  uid: c2d18f13-2eb7-457b-9b9e-d2605c5f0fe5
type: structure
